routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::prefix('/voting')->group(function () {

    Route::get('/result/{voting_id}', 'VotingController@showResult')->name('voting.result');
    Route::get('/result/{voting_id}/detailed', 'VotingController@showResultDetailed')->name('voting.result.detailed');
    Route::get('/result/{result_id}/download', 'VotingController@downloadResult')->name('voting.result.download');
    Route::get('/vote/{voting_id}', 'VotingController@doVote')->name('voting.vote');
    Route::post('/vote/{voting_id}', 'VotingController@voteStepOne')->name('voting.vote.do');
    Route::post('/vote/{voting_id}/send', 'VotingController@voteStepTwo')->name('voting.vote.send');

    Route::group(['middleware' => ['admin']], function () {

        Route::prefix('/create')->group(function () {
            Route::get('/', 'VotingController@createForm')->name('voting.create.form');
            Route::post('/', 'VotingController@create')->name('voting.create');
            Route::get('/{voting_id}/votes', 'VotingController@votesForm')->name('voting.create.votes.form');
            Route::post('/{voting_id}/votes', 'VotingController@storeVotes')->name('voting.create.votes');
        });

        Route::prefix('/delete')->group(function () {
            Route::get('/voting/{voting_id}', 'VotingController@delete')->name('voting.delete');
        });

    });
});

Route::get('/', 'HomeController@index')->name('home');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <p class="title is-4 has-text-centered">{{ __('Voting centre') }}</p>

    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    @role('admin')
        <div class="column">
            <div class="buttons is-centered">
                <a href="{{ route('voting.create.form') }}" class="button">{{ __('Create voting') }}</a>
            </div>
        </div>
    @endrole

    <br>

    <table class="table is-fullwidth" style="table-layout: fixed;">
        <thead>
            <tr>
                <th>{{ __('Voting #') }}</th>
                <th>{{ __('Voting name') }}</th>
                <th>{{ __('Voters count') }}</th>
                <th>{{ __('Actions') }}</th>
            </tr>
        </thead>
        <tbody>
            @forelse(\App\Voting::withCount('results')->get() as $voting)
            <tr>
                <td>{{ $voting->id }}</td>
                <td>{{ $voting->name }}</td>
                <td>{{ $voting->results_count }}</td>
                <td>
                    <div class="buttons">
                        @role('admin')
                            <a class="button is-danger is-outlined" href="{{ route('voting.delete', ['voting_id' => $voting->id]) }}">{{ __('Delete') }}</a>
                        @else
                            <a class="button is-info is-outlined" href="{{ route('voting.vote', ['voting_id' => $voting->id]) }}">{{ __('Do vote') }}</a>
                        @endrole
                        <a class="button is-success is-outlined" href="{{ route('voting.result', ['voting_id' => $voting->id]) }}">{{ __('Results') }}</a>
                    </div>
                </td>
            </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center">{{ __('No existed votings') }}</td>
                </tr>
            @endforelse
        </tbody>
    </table>

</div>
@endsection